config/routes.rb
MulletApp::Application.routes.draw do
  resources :tweets

  resources :boxes

  devise_for :users, controllers: {omniauth_callbacks: "omniauth_callbacks"}

  root :to => "pages#home"

end

app/models/box.rb
class Box < ActiveRecord::Base
  attr_accessible :desciption, :image, :title

  validates :user_id, presence: true

  belongs_to :user
  has_many :tweets
end

app/models/other_twitter_user.rb
class OtherTwitterUser < ActiveRecord::Base
  attr_accessible :username
end

app/models/othertwitterusers.rb
class Othertwitterusers < ActiveRecord::Base
  attr_accessible :name
end

app/models/otu.rb
class Otu < ActiveRecord::Base
  attr_accessible :name
end

app/models/tweet.rb
class Tweet < ActiveRecord::Base
  attr_accessible :user_id, :tweet_text

  #validates :box_id, presence: true

  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :omniauthable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :username
  # attr_accessible :title, :body

  has_many :tweets

  def self.from_omniauth(auth)
	  where(auth.slice(:provider, :uid)).first_or_create do |user|
	    user.provider = auth.provider
	    user.uid = auth.uid
	    user.username = auth.info.nickname
	  end
	end

	def self.new_with_session(params, session)
	  if session["devise.user_attributes"]
	    new(session["devise.user_attributes"], without_protection: true) do |user|
	      user.attributes = params
	      user.valid?
	    end
	  else
	    super
	  end
	end

	def password_required?
	  super && provider.blank?
	end

	def update_with_password(params, *options)
	  if encrypted_password.blank?
	    update_attributes(params, *options)
	  else
	    super
	  end
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/boxes_controller.rb
class BoxesController < ApplicationController
  before_filter :authenticate_user!, except: [:index]
  # GET /boxes
  # GET /boxes.json
  def index
    @boxes = Box.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @boxes }
    end
  end

  # GET /boxes/1
  # GET /boxes/1.json
  def show
    @box = Box.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @box }
    end
  end

  # GET /boxes/new
  # GET /boxes/new.json
  def new
    @box = current_user.boxes.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @box }
    end
  end

  # GET /boxes/1/edit
  def edit
    @box = current_user.boxes.find(params[:id])
  end

  # POST /boxes
  # POST /boxes.json
  def create
    @box = current_user.boxes.new(params[:box])

    respond_to do |format|
      if @box.save
        format.html { redirect_to @box, notice: 'Box was successfully created.' }
        format.json { render json: @box, status: :created, location: @box }
      else
        format.html { render action: "new" }
        format.json { render json: @box.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /boxes/1
  # PUT /boxes/1.json
  def update
    @box = current_user.boxes.find(params[:id])

    respond_to do |format|
      if @box.update_attributes(params[:box])
        format.html { redirect_to @box, notice: 'Box was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @box.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /boxes/1
  # DELETE /boxes/1.json
  def destroy
    @box = current_user.boxes.find(params[:id])
    @box.destroy

    respond_to do |format|
      format.html { redirect_to boxes_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/omniauth_callbacks_controller.rb
class OmniauthCallbacksController < Devise::OmniauthCallbacksController
	def all
		user = User.from_omniauth(request.env["omniauth.auth"])
		if user.persisted?
      flash.notice = "Signed in!"
      sign_in_and_redirect user
    else
      session["devise.user_attributes"] = user.attributes
      redirect_to new_user_registration_url
    end
	end
	alias_method :twitter, :all
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  	require 'twitter'

  	Twitter.configure do |config|
		  config.consumer_key = ENV['TWITTER_CONSUMER_KEY']
		  config.consumer_secret = ENV['TWITTER_CONSUMER_SECRET']
		  config.oauth_token = ENV['TWITTER_OAUTH_TOKEN']
		  config.oauth_token_secret = ENV['TWITTER_OAUTH_TOKEN_SECRET']
	end

	@user_tweets = Tweet.new(params[:tweet])
	@other_users_tweets = Otu.new(params[:othertwitteruser])
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  # GET /tweets
  # GET /tweets.json
  def index
    @tweets = Tweet.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @tweets }
    end
  end

  # GET /tweets/1
  # GET /tweets/1.json
  def show
    @tweet = Tweet.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @tweet }
    end
  end

  # GET /tweets/new
  # GET /tweets/new.json
  def new
    @tweet = Tweet.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @tweet }
    end
  end

  # GET /tweets/1/edit
  def edit
    @tweet = Tweet.find(params[:id])
  end

  # POST /tweets
  # POST /tweets.json
  def create
    @tweet = Tweet.new(params[:tweet])

    respond_to do |format|
      if @tweet.save
        format.html { redirect_to root_path }
        format.json { render json: @tweet, status: :created, location: @tweet }
      else
        format.html { render action: "new" }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /tweets/1
  # PUT /tweets/1.json
  def update
    @tweet = Tweet.find(params[:id])

    respond_to do |format|
      if @tweet.update_attributes(params[:tweet])
        format.html { redirect_to @tweet, notice: 'Tweet was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tweets/1
  # DELETE /tweets/1.json
  def destroy
    @tweet = Tweet.find(params[:id])
    @tweet.destroy

    respond_to do |format|
      format.html { redirect_to tweets_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/boxes_helper.rb
module BoxesHelper
end

app/helpers/omniauth_callbacks_helper.rb
module OmniauthCallbacksHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/boxes/_form.html.erb
<%= form_for(@box) do |f| %>
  <% if @box.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@box.errors.count, "error") %> prohibited this box from being saved:</h2>

      <ul>
      <% @box.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :desciption %><br />
    <%= f.text_field :desciption %>
  </div>
  <div class="field">
    <%= f.label :image %><br />
    <%= f.text_field :image %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/boxes/edit.html.erb
<h1>Editing box</h1>

<%= render 'form' %>

<%= link_to 'Show', @box %> |
<%= link_to 'Back', boxes_path %>

app/views/boxes/index.html.erb
<h1>Listing boxes</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Desciption</th>
    <th>Image</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @boxes.each do |box| %>
  <tr>
    <td><%= box.title %></td>
    <td><%= box.desciption %></td>
    <td><%= box.image %></td>
    <td><%= link_to 'Show', box %></td>
    <td><%= link_to 'Edit', edit_box_path(box) %></td>
    <td><%= link_to 'Destroy', box, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Box', new_box_path %>

app/views/boxes/new.html.erb
<h1>New box</h1>

<%= render 'form' %>

<%= link_to 'Back', boxes_path %>

app/views/boxes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @box.title %>
</p>

<p>
  <b>Desciption:</b>
  <%= @box.desciption %>
</p>

<p>
  <b>Image:</b>
  <%= @box.image %>
</p>


<%= link_to 'Edit', edit_box_path(@box) %> |
<%= link_to 'Back', boxes_path %>

app/views/layouts/_footer.html.erb
<!-- <footer>
  <p>&copy; Company 2013</p>
</footer> -->

app/views/layouts/_header.html.erb
<div class="navbar navbar-inverse navbar-fixed-top">
	<div class="navbar-inner">
		<div class="container">
			<button type="button" class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="brand" href="/">Mullet</a>
			<div class="nav-collapse collapse">
				<ul class="nav">
					<li><a href="#">About</a></li>
				</ul>
        <ul class="nav pull-right">
					<% if user_signed_in? %>
						<li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              	<img src="https://api.twitter.com/1/users/profile_image?screen_name=<%= current_user.username %>&size=mini" class="img-circle" /> <%= current_user.username %> <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to 'Edit profile', edit_user_registration_path %></li>
                <li class="divider"></li>
                <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
              </ul>
            </li>
					<% else %>
						<li><%= link_to "Sign up", new_user_registration_path %></li>
						<li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">Sign In <b class="caret"></b></a>
              <ul class="dropdown-menu">
                <li><%= link_to "Login", new_user_session_path %></li>
                <li class="divider"></li>
                <li><%= link_to "Sign in with Twitter", user_omniauth_authorize_path(:twitter) %></li>
              </ul>
            </li>
					<% end %>
				</ul>
			</div>
		</div>
	</div>
</div>

<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MulletApp</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
		<%= render 'layouts/header' %>
	<div class="container">
		<%= yield %>
		<%= render 'layouts/footer' %>
	</div>
</body>
</html>

app/views/pages/home.html.erb
<div class="hero-unit">
  <h1>Mullet.</h1>
  <p>Business is the front (-end), party in the back (-end). Sign in to access your tweets and start making boxes!</p>
  <p><a href="#" class="btn btn-primary btn-large">Learn more &raquo;</a></p>
</div>

<div class="container">
	<% if user_signed_in? %>
		<!-- <img src="https://api.twitter.com/1/users/profile_image?screen_name=<%= current_user.username %>&size=original" /> -->
		<div class="row">
			<div class="span1"></div>
			<p><a href="#" class="btn btn-primary btn-large span3" onclick="view_your_tweets()">View Your Tweets</a></p>
			<p><a href="#" class="btn btn-primary btn-large span3" onclick="view_others_tweets()">View Tweets From Others</a></p>
			<p><a href="#" class="btn btn-primary btn-large span3" onclick="view_saved_tweets()">View Your Saved Tweets</a></p>
			<div class="span1"></div>
		</div>
		
		<div id="users_tweets">
			<% Twitter.user_timeline(current_user.username, :count => 20).each do |t| %>
				<div class="tweet" data-tweet-id="<%= t.id %>">
					<%= t.text %>
					<%= form_for @user_tweets do |f| %>
						<%= f.hidden_field :user_id, :value => current_user.id %>
						<%= f.hidden_field :tweet_text, :value => t.text %>
						<%= f.submit "Save Tweet" %>
					<% end %>
					<br />
				</div>
			<% end %>
		</div>

		<div id="other_users_tweets">
			<div class = "row">
				<div class = "span4"></div>
					<%= form_for :othertwitteruser, :url => root_path, :class => 'span4' do |f| %>
						<%= f.label 'Enter the twitter username of the person you would like to view:' %>
						<%= f.text_field :name %>
						<%= f.submit "Submit" %>
					<% end %>
				<div class = "span4"></div>
				<% @selected_button = 'other_user' %>
			</div>
			<% if @other_users_tweets.name != nil %>
				<% Twitter.user_timeline(@other_users_tweets.name, :count => 20).each do |t| %>
					<div class="tweet" data-tweet-id="<%= t.id %>">
						<%= t.text %>
						<br />
					</div>
				<% end %>
			<% end %>
		</div>

		<div id="saved_tweets">
			<% Tweet.all().each do |t| %>
					<div class="tweet" data-tweet-id="<%= t.id %>">
						<%= t.tweet_text %>
						<br />
					</div>
			<% end %>
		</div>
	<% else %>
</div>
<% end %>

app/views/tweets/_form.html.erb
<%= form_for(@tweet) do |f| %>
  <% if @tweet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tweet.errors.count, "error") %> prohibited this tweet from being saved:</h2>

      <ul>
      <% @tweet.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tweets/edit.html.erb
<h1>Editing tweet</h1>

<%= render 'form' %>

<%= link_to 'Show', @tweet %> |
<%= link_to 'Back', tweets_path %>

app/views/tweets/index.html.erb
<h1>Listing tweets</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @tweets.each do |tweet| %>
  <tr>
    <td><%= tweet.id %></td>
    <td><%= link_to 'Show', tweet %></td>
    <td><%= link_to 'Edit', edit_tweet_path(tweet) %></td>
    <td><%= link_to 'Destroy', tweet, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Tweet', new_tweet_path %>

app/views/tweets/new.html.erb
<h1>New tweet</h1>

<%= render 'form' %>

<%= link_to 'Back', tweets_path %>

app/views/tweets/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_tweet_path(@tweet) %> |
<%= link_to 'Back', tweets_path %>